### ISSUE TITLE
Getting started shows twice...

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#114]
**Describe the bug**
When I click Help =-> Getting Started, it first displays as a dialog, and then as an HTML page in my default browser. 

**Application**: Brain Simulator

**Module/Network**: N/A

**To Reproduce**
1. Choose Help => Getting Started.
2. Notice dialog shows, click OK.
3. Notice default browser comes up with the exact same information again. 

**Expected behavior**
I prefer the latter, because opening getting started by default for new users is IMHO not needed. Most users know to turn to the help menu for info, or press F1 which now also shows the getting started. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version: 2021-04-23 master

**Comment by FutureAIGuru** [comment]
I’ll fix the bug.
Here’s the trade-off:
If display within the program, I can trap links so that I could make the network names hot and actually load the network if you clicked them. If the display is in the browser, it has a lot more flexibility.
Do you think the first feature is valuable?


From: Andre Slabber ***@***.***>
Sent: Friday, April 23, 2021 1:17 AM
To: FutureAIGuru/BrainSimII ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FutureAIGuru/BrainSimII] Getting started shows twice... (#114)


Describe the bug
When I click Help =-> Getting Started, it first displays as a dialog, and then as an HTML page in my default browser.

Application: Brain Simulator

Module/Network: N/A

To Reproduce
Steps to reproduce the behavior:

  1.  Choose Help => Getting Started.
  2.  Notice dialog shows, click OK.
  3.  Notice default browser comes up with the exact same information again.

Expected behavior
I prefer the latter, because opening getting started by default for new users is IMHO not needed. Most users know to turn to the help menu for info, or press F1 which now also shows the getting started.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

  *   OS: Windows 10 Pro 20H2
  *   Version: 2021-04-23 master

Add any other context about the problem here.

**Comment by Moorelife** [comment]
Hi Charlie,

Hadn't thought of that, but actually, that might be useful.
On the other hand, I think there is this:


* We will also have the library menu which will display them in the same order if you fix that one change you already have listed.
  * Most users will immediately check the box about not showing it and will never use it again.
  * I can look into adding registry keys in the installer that will add "Open with BrainSimII" to the right-click menu for XML files.
  Nothing else comes to mind right now.


Cheers,

André

**Comment by Moorelife** [comment]
Fixed just now.
