### ISSUE TITLE
Exception in Module should offer to remove module

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#142]
**Describe the bug**
If an exception is encountered in a module, a messageBox will be shown repeatedly, every time the module is called.

**Application**: Brain Simulator, 

**Expected behavior**
The message box should offer to remove the module from the network so that repeated message boxes won't impede the rest of the program.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version [v0.9a]

**Comment by Moorelife** [comment]
Please reconsider: if a repeated message is shown, then the user may want to fix the module rather than discard it altogether.

Why not implement a "Prevent Module from showing more messages" and prevent the message box from being shown. You might even reset that flag as soon as the Initialize is called, so the user can check if the problem was fixed.

**Comment by Moorelife** [comment]
This indeed now happens!
