### ISSUE TITLE
Network Properties stops neuron firings.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#144]
**Describe the bug**
Having the active network running at any speed, choosing File => Network Properties will halt any firing, but will keep the engine running. This may be related to #107, but I would hardly call it occasional, because the scenario it completely reliable.

**Application**: Brain Simulator, Neuron Engine

**Module/Network**: See attached network:
[Hemispheres.zip](https://github.com/FutureAIGuru/BrainSimII/files/6374939/Hemispheres.zip)

**To Reproduce**
1. Unzip and load attached hemispheres.xml.
2. Click 'Zoom All'
3. Notice the ten white neurons (continuous firing) in the center. 
4. Click File => Properties, notice the random color blinking stops, but engine is still running fine.
5. Click cancel on the properties dialog.
6. Notice firing won't continue unless you fire the neuron indicated by the arrow in the screenshot (ID 675)

**Expected behavior**
If I have the engine running immediately before asking for network properties, I expect it to at least continue afterwards. And since rows and columns can be changed in this dialog, I even expect the engine to stop running before we attempt to process this changed rows and/or columns. Of course if it was running before, it should also be started again. 

**Screenshots**
![IMG_20210426_091748](https://user-images.githubusercontent.com/11266191/116045270-2c05eb00-a672-11eb-8f64-9cf57085d5a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version: 2021-04-26 master

**Comment by Moorelife** [comment]
I've added SuspendEngine() and ResumeEngine() calls around the ShowDialog() of the Properties dialog, but even then the number of firing neurons in the aforementioned network drops from around 20 to ZERO. Surely, Suspend and Resume should be seamless, and should keep their charges.

**Comment by FutureAIGuru** [comment]
The engine loop is always running. If you suspend the engine, the loop continues to run but never calls any fire methods. The loop is still running, it just can’t do anything enginewise.

When the neuron display needs to update, it just sets a flag. The engine loop checks the flag and updates the display if necessary. That way, the display can only update between firing cycles because the engine firing is never actually running while the display updates. So the display is always a snapshot of the array.

The problem of the firedCount dropping will probably go away if the bigger progressDialog problem is fixed:
The progressDialog must run in the UI thread because all display objects must run in that thread. MutualSuppressesion (my test example) runs in that thread as well so it blocks the UI thread while it is running. But that blocking also prevents the ProgressDialog from updating. So there is the added  AllowUIToUpdate() which lets the progressBar update but also creates all the problems because then you can also start another mutual suppression while  the first mutual suppression is still running. This definitely lets the cat among the pixies.

You can’t make the ProgressDialog Modal because then it blocks the mutalSupression from completing too. I tried it.

A solution will emerge, I am sure.
I’m looking into the difficulty of setting a flag whenever the progressDialog is visible which keeps the rest of the commands from running. There might be an easy way to do that.

**Comment by Moorelife** [comment]
The normal approach to any long-lived activity in a Windows program is to put it in a separate thread so the GUI thread is not unduly blocked, and the activity gets to complete without being block too. Problem remaining then is a communication between the two threads to report progress.

**Comment by Moorelife** [comment]
Hmm, today's state of the program does absolutely NO random synapses whatsoever. It very briefly flashes the progress bar on screen, but then leaves the selection on screen without any added synapses!

**Comment by FutureAIGuru** [comment]
I found a problem a bit ago with the cancelbutton not being reset so was cancelling the file load right off the bat but I fixed it and checked it in.
Charlie

**Comment by Moorelife** [comment]
Currently the BasicNeurons network will suspend the network when properties are shown, and a firing neuron is shown in example #1. However, when properties is canceled or OK'ed, the next neuron in the loop won't fire.
