### ISSUE TITLE
Neuron labels with selection don't number properly.

### ISSUE THREAD

**Issue by FutureAIGuru** [FutureAIGuru/BrainSimII#167]
**Describe the bug**
If you add a label to a neuron which is within a selection, it will be autonumbered. But the numbering starts a one greater than the number you enter. It works properly if the neuron you label is not within the selection.

**Application**: Brain Simulator, 

**To Reproduce**
1. Select a block of neurons
2. Click on the first
3. Label it as A0
4. Note it is labeled A1.

**Expected behavior**
it should be labeled A0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version [v0.9a]

**Comment by Moorelife** [comment]
Do you want it to be labeled A0 if you just label it A? Because it used to be that the current neuron in a selection was labeled without a number, and all others received numbered labels starting at 1. I changed that because the inconsistency in that approach messed with the tool tips. But having it start at 0 rather than 1 is a trivial change.

**Comment by FutureAIGuru** [comment]
I was confused when I put in a label of A0 and the label showed as A1. If I put in A, I expect the neuron to be labeled A and other neurons would start with A0.

**Comment by Moorelife** [comment]
Yup, it now does what you said it should do. Although I am not sure we do not also want to number tool tips if they are applied to the whole selection.

**Comment by Moorelife** [comment]
Since label numbering is now OK, I will close this and open a fresh issue for the tool tip numbering.
