### ISSUE TITLE
Having 'no network' when started with shift pressed causes exceptions in a few places.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#170]
**Describe the bug**
We used to have a default network when Brain Simulator II was started with shift pressed to avoid loading the current network. Now it starts with no network at all, which can cause null reference exceptions in a number of places.

**Application**: Brain Simulator, Neuron Engine

**Module/Network**: N/A

**To Reproduce**
1. Start Brain Simulator II with shift pressed, it loads no network.
2. Click New, this crashes because it attempts to get the old value for Show All Synapses.
3. Fix this, then try again and new network shows.
4. Click Cancel, the New again, exceptions are now caused because SuspendEngine() and ResumeEngine() are not null-proof.

**Expected behavior**
I expect either no null reference exception on the 'no network' condition, or 'no network' should be 'default new network' again. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-06-04 master

**Comment by FutureAIGuru** [comment]
The problem which the shift-key was intended to solve is that it is pretty to modify a module in such a way that the xml file becomes invalid. When I did this, it became impossible to start the program because it always tried to reload the file on startup.

Perhaps we have solved this problem in other ways (try-catch) so the shift-key option is no longer needed.

**Comment by Moorelife** [comment]
I added a few minor changes to fix this, so we can keep it in.
