### ISSUE TITLE
Issue when loading any file

### ISSUE THREAD

**Issue by Delcos** [FutureAIGuru/BrainSimII#207]
Does anyone have a fix for this issue, it happens when trying to load any of the included files or my own. Thanks.

![Screenshot (14680)](https://user-images.githubusercontent.com/28798918/182462497-c8e87a47-cf29-489f-b660-df6d6072501d.png)

**Comment by FutureAIGuru** [comment]
We’re working on a fix for this one which is specific to the networks which use the Windows speech system.  It’s a change in the way Windows (.net) needs its system dlls installed.

Does the “Basic Neurons” network load?

From: Delcos ***@***.***>
Sent: Tuesday, August 2, 2022 1:00 PM
To: FutureAIGuru/BrainSimII ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FutureAIGuru/BrainSimII] Issue when loading any file (Issue #207)


Does anyone have a fix for this issue, it happens when trying to load any of the included files or my own. Thanks.

[Screenshot (14680)]<https://user-images.githubusercontent.com/28798918/182462497-c8e87a47-cf29-489f-b660-df6d6072501d.png>

**Comment by Delcos** [comment]
I checked and basic neurons does load correctly. Is there a way to get the dlls correctly set up/installed?

**Comment by FutureAIGuru** [comment]
This should now be fixed in v1.6.7.  (just uploaded)
Download and reinstall and all should be better.

**Comment by Delcos** [comment]
Great work. Thanks for the quick fix.
