### ISSUE TITLE
Network speed 10 hangs neuron engine when firing history is on.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#39]
**Describe the bug**
The combination of neuron engine speed 10 and firing history on hangs the engine.

**Application**: Brain Simulator, Neuron Engine

**Module/Network**: N/A

**To Reproduce**
1. on a new network, set network speed to 5.
2. right click a neuron, set it to random, charge 1, mean 5, std dev 5.
3. check show firing history and press enter.
4. notice engine running, then move speed control to 10.
5. notice firing history freezes, as does neuron engine. 
6. ending brain simulator is now ONLY POSSIBLE by killing it from the task manager.

**Expected behavior**
Firing history is useless at speed 10 anyway, so it is best to deactivate it when speed is cranked up to ten, and the checkbox for it disabled if speed is already at ten. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 1.0

**Comment by FutureAIGuru** [comment]
Looks like with a high engine speed, ;you very rapidly collect so much History data that  the repaint time on the History window brings the UI to a halt. The engine continues to run.  Also, if there are no spikes in the history, there is no problem so the issue is involved in the paint time for drawing the spikes.  Some sort of limit should fix the problem, e.g. only every paint 1000 history points, then require scrolling.

**Comment by Moorelife** [comment]
Nicely fixed in the 2021-04-17 master.
