### ISSUE TITLE
NeuronServer throws an exception when run from the build location

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#56]
**Describe the bug**
the NeuronServer throws an exception when run from the build location, complaining about the NeuronEngineWrapper.
Even copying in those files from their original location will not solve this. 

**Application**: Brain Simulator

**Module/Network**: N/A

**To Reproduce**
1. Download Github ZIP file.
2. Open solution in Visual Studio.
3. Rebuild All.
4. Got to the folder where NeuronServer.exe is, and start it.
5. Notice the error below:

**Expected behavior**
No error messages, and a running NeuronServer.

**Screenshots**
![IMG_20210415_122444](https://user-images.githubusercontent.com/11266191/114855622-75d71180-9de6-11eb-9607-f9118dfa8ea7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-04-15  master

**Comment by Moorelife** [comment]
Ah, tester error: I need to start it from the obj folder, and not from the bin folder.

**Comment by FutureAIGuru** [comment]
Also, I’ll need to add a version check. If the engines are different versions from the UI, it would be easy to have a crash on older ones. Ex: if you disable a neuron and then run a server prior to that addition, it will likely crash. Because it’s machine-to-machine, there’s no intrinsic check like there is on local .dlls.

From: Andre Slabber ***@***.***>
Sent: Thursday, April 15, 2021 3:34 AM
To: FutureAIGuru/BrainSimII ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FutureAIGuru/BrainSimII] NeuronServer throws an exception when run from the build location (#56)


Describe the bug
the NeuronServer throws an exception when run from the build location, complaining about the NeuronEngineWrapper.
Even copying in those files from their original location will not solve this.

Application: Brain Simulator

Module/Network: N/A

To Reproduce
Steps to reproduce the behavior:

  1.  Download Github ZIP file.
  2.  Open solution in Visual Studio.
  3.  Rebuild All.
  4.  Got to the folder where NeuronServer.exe is, and start it.
  5.  Notice the error below:

Expected behavior
No error messages, and a running NeuronServer.

Screenshots
If applicable, add screenshots to help explain your problem.
[IMG_20210415_122444]<https://user-images.githubusercontent.com/11266191/114855622-75d71180-9de6-11eb-9607-f9118dfa8ea7.png>

Desktop (please complete the following information):

  *   OS: Winodws 10 Pro 20H2
  *   Version 2021-04-15 master

Add any other context about the problem here.

**Comment by Moorelife** [comment]
Yup, DEFINITELY!

**Comment by FutureAIGuru** [comment]
I’m finding a slew of other bugs in the NeuronServer interface. I haven’t touched it in a few months while I’ve been advancing other things.
I’m just running on a local machine and I posted a few bugs but will suspend until I can get something to work.
Charlie

**Comment by Moorelife** [comment]
Hi Charlie,

Good one to let simmer a while, the server thing is nice but not something that is essential in this stage of development.


Best Regards,

André
