### ISSUE TITLE
Creation of ModulesCamera crashes Brain Simulator

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#81]
**Describe the bug**
If I create a ModuleCamera Module on an empty network, the simulator crashes.

**Application**: Brain Simulator

**Module/Network**: new network

**To Reproduce**
1. Make a new default network.
2. Select an area of some size, say 20x10.
3. Right-Click, and make it type ModuleCamera.
4. Watch the simulator crash without warning. 

**Expected behavior**
I can understand that the Camera Module needs some prerequisites, but even with my camera attached I get a crash.
I would at least expect a message as to why a Camera Module can't be created, but certainly no crash. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-04-19 master

**Comment by FutureAIGuru** [comment]
This one works for me both with and without a camera attached. Does the supplied CameraTest module also fail?
Charlie

From: Andre Slabber ***@***.***>
Sent: Monday, April 19, 2021 9:58 AM
To: FutureAIGuru/BrainSimII ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FutureAIGuru/BrainSimII] Creation of ModulesCamera crashes Brain Simulator (#81)


Describe the bug
If I create a ModuleCamera Module on an empty network, the simulator crashes.

Application: Brain Simulator

Module/Network: new network

To Reproduce
Steps to reproduce the behavior:

  1.  Make a new default network.
  2.  Select an area of some size, say 20x10.
  3.  Right-Click, and make it type ModuleCamera.
  4.  Watch the simulator crash without warning.

Expected behavior
I can understand that the Camera Module needs some prerequisites, but even with my camera attached I get a crash.
I would at least expect a message as to why a Camera Module can't be created, but certainly no crash.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

  *   OS: Windows 10 Pro 20H2
  *   Version 2021-04-19 master

Add any other context about the problem here.

**Comment by Moorelife** [comment]
Clarification: I used the release version in the installer, and that crashes. But apparently that is because some files are still missing from the installer script. I will see what to add so it does not crash.

**Comment by FutureAIGuru** [comment]
Likely webcamlib.dll or webcamwrapper.dll

**Comment by FutureAIGuru** [comment]
BUT, you didn’t get a error screen. I’ve previously had reports from users getting error messages for missing .dlls. I’ll have to check again.
Charlie

**Comment by Moorelife** [comment]
Probably because they tried it from Visual Studio, I've had those before.
I was testing straight from the end-user perspective
AFTER having created and run the installer.

**Comment by Moorelife** [comment]
By the way, if you reply to github via mail, remove the previous texts. It makes for a much cleaner view on Github...

**Comment by FutureAIGuru** [comment]
OK

**Comment by Moorelife** [comment]
Problem fixed.
