### ISSUE TITLE
Max Possible Neurons in new network is sometimes not shown.

### ISSUE THREAD

**Issue by Moorelife** [FutureAIGuru/BrainSimII#87]
**Describe the bug**
I cannot yet find the exact root cause of this, but I have noticed on several occasions that even though the memory counts are there, the "Max Neurons Possible in RAM" value is sometimes not shown.

**Application**: Brain Simulator

**Module/Network**: new network

**To Reproduce**
1. Play around with the Brain Simulator repeatedly creating new networks, etc.
2. At some point you will notice the mentioned fields value disappearing.

**Expected behavior**
The value should always be there, since it only depends on local memory consumption.

**Screenshots**
![no_value](https://user-images.githubusercontent.com/11266191/115291926-9dffa100-a155-11eb-96b1-ba26a921897b.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  20H2
 - Version 2021-04-19 master

**Comment by FutureAIGuru** [comment]
I can fix this…if the number has to many wide digits, it won’t fit in the textbox window.
Charlei

From: Andre Slabber ***@***.***>
Sent: Monday, April 19, 2021 12:25 PM
To: FutureAIGuru/BrainSimII ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FutureAIGuru/BrainSimII] Max Possible Neurons in new network is sometimes not shown. (#87)


Describe the bug
I cannot yet find the exact root cause of this, but I have noticed on several occasions that even though the memory counts are there, the "Max Neurons Possible in RAM" value is sometimes not shown.

Application: Brain Simulator

Module/Network: new network

To Reproduce
Steps to reproduce the behavior:

  1.  Play around with the Brain Simulator repeatedly creating new networks, etc.
  2.  At some point you will notice the mentioned fields value disappearing.

Expected behavior
The value should always be there, since it only depends on local memory consumption.

Screenshots
If applicable, add screenshots to help explain your problem.
[no_value]<https://user-images.githubusercontent.com/11266191/115291926-9dffa100-a155-11eb-96b1-ba26a921897b.jpg>

Desktop (please complete the following information):

  *   OS: Windows 10 Pro 20H2
  *   Version 2021-04-19 master

Add any other context about the problem here.

**Comment by Moorelife** [comment]
New network dialog was changed, now has enough space for the value.

**Comment by Moorelife** [comment]
Shortened labels so more room for values.
